apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pleiepenger-oppgave
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
    - https://pleiepenger-oppgave.nais.adeo.no
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  env:
    - name: OPPGAVE_BASE_URL
      value: https://oppgave.nais.adeo.no
    - name: SPARKEL_BASE_URL
      value: https://sparkel.nais.adeo.no
    - name: NAIS_STS_DISCOVERY_ENDPOINT
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration